language: cpp
compiler: gcc
install:
  - sudo apt-get install libboost1.48-all-dev libprotobuf-dev protobuf-compiler liblog4cplus-dev libcrypto++-dev libfuse-dev python-crypto python-eventlet python-protobuf
script:
  - cmake .
  - make
  - ctest -V

