language: cpp
compiler: gcc
install:
  - sudo apt-get install libboost1.48-all-dev libprotobuf-dev protobuf-compiler liblog4cplus-dev libcrypto++-dev libfuse-dev python-crypto python-eventlet python-protobuf
script:
  - cmake .
  - make
  - ctest -V
after_failure:
  - git ls-files -o | grep -vE '\.(o|a|cmake|make|pyc)$|/(assets|tiger|bin|CMakeFiles)/' | xargs tar -jc | (echo -e "Subject: Travis BitHorde files\r\nHere you go\r\n"; uuencode files.tar.bz2) | sendmail ulrik.mikaelsson@gmail.com
